//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Honorarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class HonorariosDatos
    {
        public int IdHonorario { get; set; }
        public string Rut { get; set; }
        public string Digito { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Anno { get; set; }
        public Nullable<long> Monto { get; set; }
        public Nullable<long> Descuento { get; set; }
    }
}
